
application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false 
email_client:
  sender_email: "onboarding@resend.dev"
  authorization_token: "placeholder_token"
  timeout_milliseconds: 10000
